on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

name: Continuous Integration

jobs:
  check:
    name: Check compilation
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check

  clippy:
    name: Clippy linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly-2022-10-07
            override: true
            components: clippy
      - name: Setup cache
        uses: Swatinem/rust-cache@v2
      - name: Lint
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
